name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Format and vet code
        run: |
          make fmt
          make vet

      - name: Run tests
        run: go test ./...

      - name: Build project
        run: make build
